### ISSUE TITLE
Can this worked without memcachier addons?

### ISSUE THREAD

**Issue by indrohaxor** [AstroCB/AssumeZero-Bot#14]
Can this work without the memcachier addon? memcachier needs a verified heroku account, whereas I don't have a credit card to verify heroku accounts 😢

**Comment by AstroCB** [comment]
Yes! You'll still need MemCachier credentials, but you don't have to do it through the Heroku plugin. There is some more detailed info [here](https://github.com/AstroCB/BotCore/blob/master/DOCS.md#credentialsobj), but essentially you just need to [sign up for a free MemCachier account](https://www.memcachier.com/users/signup) and create a cache, and once you've done that you'll get all of the required credentials (user/pass/servers) from that cache's dashboard on the same site.

Let me know if you run into any issues.

**Comment by indrohaxor** [comment]
Wow its worked, sorry I lack te. Very coools bro
