### ISSUE TITLE
Reminders should reply to an earlier message for easy context/scroll

### ISSUE THREAD

**Issue by gharris1727** [AstroCB/AssumeZero-Bot#20]
Some reminders may be created far in the future, such that the original context for the reminder has been forgotten. In addition to the current context message, the reminder should also reply to the earlier message (either the one which created the reminder, or one of the warning messages) so that it's easy to click on the replied message to scroll back for context.

**Comment by BotolMehedi** [comment]
@AstroCB 
![Screenshot_2021-05-01-15-49-07](https://user-images.githubusercontent.com/64999484/116778639-f5c2d400-aa94-11eb-829c-953059642b7d.png)
![Screenshot_2021-05-01-15-48-12](https://user-images.githubusercontent.com/64999484/116778646-f9565b00-aa94-11eb-8ed0-9fec9394801a.png)

How to solved this problem??? My Facebook account email & password is correct. But it's showing wrong. why?? 😑😑😑
