### ISSUE TITLE
Custom command to mention a certain group of members.

### ISSUE THREAD

**Issue by jovvybersamin** [AstroCB/AssumeZero-Bot#22]
Hi,

Where I will start to create my own command let say I only want to mention members that their nicknames start at "GOLD-" or "SILVER-"

so if  I type physics @@all-gold or physics @@all-silver it will mention the specific members

Thanks!

**Comment by AstroCB** [comment]
Hi, this command exists – check out `physics help group`.

**Comment by jovvybersamin** [comment]
I see, but the users need to subscribe to it manually, what I want is it will search all members where their nicknames start at "GOLD-".

**Comment by AstroCB** [comment]
Ah, I see. You can also subscribe the users by the way; they don't have to do it themselves. 

If you really want to do it based off of nicknames, you'll have to modify the mention groups code. Check out `passive.js` to see how that's done; you can probably use `@@all`'s implementation as a guide. You can get nickname information from the `groupInfo` object. 

I'd suggest taking a look at the README if you haven't already to get a basic idea of the bot structure.

**Comment by jovvybersamin** [comment]
@AstroCB Thanks, I was able to add the feature I want.

**Comment by AstroCB** [comment]
Great!
