### ISSUE TITLE
Cannot read property 'successful_results' of undefined

### ISSUE THREAD

**Issue by jovvybersamin** [AstroCB/AssumeZero-Bot#23]
getSeqId TypeError: Cannot read property 'successful_results' of undefined
ERR! getSeqId   at /app/node_modules/facebook-chat-api/src/listenMqtt.js:532:41
...

The error came from facebook-chat-api

**Comment by AstroCB** [comment]
Hmm, haven't seen that one. I'd recommend reporting it on [their repo](https://github.com/Schmavery/facebook-chat-api).
