### ISSUE TITLE
Login Approval

### ISSUE THREAD

**Issue by jovvybersamin** [AstroCB/AssumeZero-Bot#24]
For the last few days, I've been experiencing this issue.

2020-09-11T04:30:49.340582+00:00 app[web.1]: Logging in with credentials...
2020-09-11T04:30:55.693878+00:00 app[web.1]: ERR! login login-approval
2020-09-11T04:30:55.694162+00:00 app[web.1]: Fatal error: failed login with credentials

Two of my dummy FB accounts are already blocked/disabled.

Do we have a workaround for this?

**Comment by AstroCB** [comment]
Unfortunately not – just an occupational hazard unfortunately, given this is an unofficial API that carries with it a level of risk. I've done a lot of work to mitigate the risk of this happening, most of which is bundled in [BotCore](https://github.com/AstroCB/BotCore). The BotCore integration handles some caching of logins to prevent this, and I also recommend using a process manager to periodically restart the bot every ~30m or so, which will look more like organic logins.

**Comment by gionstegmann** [comment]
Has anyone been able to use the bot lately? 
I also get a similar error when restarting the app on heroku. 

> 2020-12-30T17:52:33.240050+00:00 app[web.1]: 0|assumezero-bot  | Bot 100041587845629 logging in locally with trigger "mich".
> 2020-12-30T17:52:33.310574+00:00 app[web.1]: 0|assumezero-bot  | Logging in with credentials...
> 2020-12-30T17:52:34.890474+00:00 app[web.1]: 0|assumezero-bot  | ERR!
> 2020-12-30T17:52:34.893338+00:00 app[web.1]: 0|assumezero-bot  |  
> 2020-12-30T17:52:34.895386+00:00 app[web.1]: 0|assumezero-bot  | login
> 2020-12-30T17:52:34.897799+00:00 app[web.1]: 0|assumezero-bot  |  Wrong username/password.
> 2020-12-30T17:52:34.900810+00:00 app[web.1]: 0|assumezero-bot  | Fatal error: failed login with credentials

The FB account was just created. Maybe I have to leave it some time until FB sees it as a "real" account? I'm wondering if adding friends, sending messages, adding a profile pic etc. works to accelerate this

**Comment by AstroCB** [comment]
Mine is currently up and running. 

It's hard to say exactly how Facebook decides which accounts to flag, but they keep that close to the vest for security reasons.

If you're getting a failed login, you probably need to log in manually on the web and pass a security checkpoint before updating your password, which should allow you to log in again via the bot.

I haven't found any foolproof ways of avoiding this occasional inconvenience, but the bot broadcasts a `/healthcheck` endpoint which you should be able to access from your deployed Heroku instance, and I've had limited success with a cronjob that pings this endpoint occasionally and alerts me if it's no longer logged in.

**Comment by gionstegmann** [comment]
Works now, thanks for the update!
