### ISSUE TITLE
How do I add commands?

### ISSUE THREAD

**Issue by KoreanPizzaGuy** [AstroCB/AssumeZero-Bot#29]

**Comment by AstroCB** [comment]
Hi! You'll probably want to start in [`commands.js`](https://github.com/AstroCB/AssumeZero-Bot/blob/master/src/commands.js), which is where you define the schema for the command and associated info for the help entry. After that, head to [`runcommand.js`](https://github.com/AstroCB/AssumeZero-Bot/blob/master/src/runcommand.js) and add an entry to the `func` dict to describe what to do when your command is called.

There are plenty of examples in there that should give you a good idea of how to handle input/access the db/other assorted tasks. Good luck!
