### ISSUE TITLE
ERROR while deploying on Heroku

### ISSUE THREAD

**Issue by FabyoSK** [AstroCB/AssumeZero-Bot#49]
I got this error while the bot was deploying

the complete log:

-----> Building on the Heroku-20 stack
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  12.18.2
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.18.2...
       Downloading and installing node 12.18.2...
       Using default npm version: 6.14.5
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules
       npm ERR! Error while executing:
       npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/Schmavery/facebook-chat-api.git
       npm ERR! 
       npm ERR! Host key verification failed.
       npm ERR! fatal: Could not read from remote repository.
       npm ERR! 
       npm ERR! Please make sure you have the correct access rights
       npm ERR! and the repository exists.
       npm ERR! 
       npm ERR! exited with error code: 128
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.wMef9/_logs/2021-02-13T20_13_27_425Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by AstroCB** [comment]
Are you deploying the latest commit from master in this repo? If not, can you link which commit you're deploying?

**Comment by FabyoSK** [comment]
I try to deploy this commit https://github.com/FabyoSK/AssumeZero-Bot/commit/67e678913d8ff9ad820dd174347b006699461910 
but I got the error, i try fix it but nothing works: https://github.com/FabyoSK/AssumeZero-Bot/commits/master

**Comment by AstroCB** [comment]
Try setting `USE_NPM_INSTALL` to `true` in your Heroku config vars and redeploying.

**Comment by FabyoSK** [comment]
Thanks, it works
