### ISSUE TITLE
Bot Not Started

### ISSUE THREAD

**Issue by BotolMehedi** [AstroCB/AssumeZero-Bot#54]
@AstroCB 
![Screenshot_2021-05-01-15-49-07](https://user-images.githubusercontent.com/64999484/116778639-f5c2d400-aa94-11eb-829c-953059642b7d.png)
![Screenshot_2021-05-01-15-48-12](https://user-images.githubusercontent.com/64999484/116778646-f9565b00-aa94-11eb-8ed0-9fec9394801a.png)

How to solved this problem??? My Facebook account email & password is correct. But it's showing wrong. why?? 😑😑😑

**Comment by AstroCB** [comment]
Please do not spam unrelated issues in this repository.
