### ISSUE TITLE
I don't know how to run BOT, open bot, log in bot

### ISSUE THREAD

**Issue by xuanhai0913** [AstroCB/AssumeZero-Bot#56]
Looking at the newly downloaded files is so confusing
Is there any video on how to set up bots to run?
If yes, please give me the link

**Comment by AstroCB** [comment]
Hi there – there isn't a video, but the README gives a pretty detailed look on how to get it set up, and there are a few other issues in this repo where it's explained as well, namely #13 and [the BotCore docs](http://cameronbernhardt.com/BotCore/).

**Comment by xuanhai0913** [comment]
Tôi không thể cài memciar
